package mehiz.abdallah.progres.api.dto

import kotlinx.serialization.Serializable

@Serializable
data class StudentCardDto(
  val anneeAcademiqueCode: String,
  val anneeAcademiqueId: Long,
  val cycleCode: String,
  val cycleId: Long,
  val cycleLibelleLongLt: String,
  val dossierEtudiantId: Long,
  val fraisInscriptionPaye: Boolean? = null,
  val id: Long,
  val individuDateNaissance: String,
  val individuId: Long,
  val individuLieuNaissance: String,
  val individuLieuNaissanceArabe: String,
  val individuNomArabe: String,
  val individuNomLatin: String,
  val individuPrenomArabe: String,
  val individuPrenomLatin: String,
  val lastMoyenne: Double,
  val llEtablissementArabe: String,
  val llEtablissementLatin: String,
  val moyenneBac: Double,
  val nin: String,
  val niveauCode: String,
  val niveauId: Long,
  val niveauLibelleLongAr: String,
  val niveauLibelleLongLt: String,
  val niveauRang: Long,
  val numeroInscription: String,
  val numeroMatricule: String,
  val ofCodeDomaine: String,
  val ofCodeFiliere: String,
  val ofCodeSpecialite: String? = null,
  val ofIdDomaine: Long,
  val ofIdFiliere: Long,
  val ofIdSpecialite: Long? = null,
  val ofLlDomaine: String,
  val ofLlDomaineArabe: String,
  val ofLlFiliere: String,
  val ofLlFiliereArabe: String,
  val ofLlSpecialite: String? = null,
  val ofLlSpecialiteArabe: String? = null,
  val ouvertureOffreFormationId: Long,
  val photo: String,
  val refCodeCycle: String,
  val refCodeEtablissement: String,
  val refEtablissementId: Long,
  val refLibelleCycle: String,
  val refLibelleCycleAr: String,
  val transportPaye: Boolean? = null,
  val situationId: Long,
)
