name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      #- name: Set up XCode
      #  uses: maxim-lobanov/setup-xcode@v1
      #  with:
      #    xcode-version: "15.2.0"

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew detekt assembleRelease

      - name: Upload the universal artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk
          name: progres

